I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 224, in script
    python:
  File "game/script.rpy", line 229, in <module>
    response = urllib2.urlopen(req, json.dumps(data))
HTTPError: HTTP Error 500: INTERNAL SERVER ERROR

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 224, in script
    python:
  File "/Volumes/renpy-7.4.11-sdk/renpy-7.4.11-sdk/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Volumes/renpy-7.4.11-sdk/renpy-7.4.11-sdk/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 229, in <module>
    response = urllib2.urlopen(req, json.dumps(data))
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/urllib2.py", line 154, in urlopen
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/urllib2.py", line 435, in open
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/urllib2.py", line 548, in http_response
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/urllib2.py", line 473, in error
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/urllib2.py", line 407, in _call_chain
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 500: INTERNAL SERVER ERROR

Darwin-20.6.0-x86_64-i386-64bit
Ren'Py 7.4.11.2266
R4TW 
Sun May 22 05:53:06 2022
